name: ci
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "coreweave"
  push:
    branches:
      - "coreweave"
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.22.x
          - 1.21.x
          - 1.20.x
        os:
          - macos
          - ubuntu
          - windows

    name: build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - run: make build

  test:
    strategy:
      matrix:
        go-version:
          - 1.22.x
          - 1.21.x
          - 1.20.x
        os:
          - macos
          - ubuntu
          - windows

    name: test (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    env:
      GOFLAGS: ${{ matrix.os == 'macos' && '-ldflags=-linkmode=external' || '' }}
    services:
      minio:
        image: ${{ (matrix.os == 'ubuntu') && 'bitnamilegacy/minio:2023.7.18' || ''}}
        ports:
          - 45677:9000
        options: >-
          --health-cmd "curl -I http://localhost:9000/minio/health/live -s"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - run: make test
      env:
        S5CMD_TEST_ENDPOINT_URL: ${{ (matrix.os == 'ubuntu') && 'http://localhost:45677' || '' }}
  qa:
    strategy:
      matrix:
        go-version:
          - 1.22.x
          - 1.21.x
          - 1.20.x
        os:
          - ubuntu

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - run: make bootstrap
    - run: make check
