name: goreleaser
on:
  workflow_dispatch: {}
  push:
    branches:
      - "coreweave"
jobs:
  caios_test:
    name: caios-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22.x
      - run: make test_without_race
        env:
          S5CMD_ACCESS_KEY_ID: ${{ secrets.S5CMD_CAIOS_ACCESS_KEY_ID }}
          S5CMD_SECRET_ACCESS_KEY: ${{ secrets.S5CMD_CAIOS_SECRET_ACCESS_KEY }}
          S5CMD_ENDPOINT_URL: https://cwobject.com
          S5CMD_IS_VIRTUAL_HOST: 1
          S5CMD_REGION: ${{ secrets.S5CMD_CAIOS_REGION }}
          S5CMD_I_KNOW_WHAT_IM_DOING: 1

  goreleaser:
    needs: [ caios_test ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Get tag
        id: get_tag
        run: |
          git remote add upstream https://github.com/peak/s5cmd.git
          git fetch --tags upstream
          VERSION=$(git describe --tags --exclude '*-' --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "short_sha=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: '1.18.2'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.get_tag.outputs.version }}-${{ steps.get_tag.outputs.short_sha }}

